# Generated by Django 6.0.6 on 2026-08-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='articles',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=50),
        ),
    ]
