# Generated by Django 6.0.6 on 2026-08-13 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_status_alter_articles_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesversion',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=None, null=True, size=1536),
        ),
    ]
