apiVersion: v1
kind: ConfigMap
metadata:
  name: hims-kb-config
  namespace: hims-kb
  labels:
    app.kubernetes.io/name: hims-kb
data:
  DJANGO_SETTINGS_MODULE: "hims_kb.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: ""
  CSRF_TRUSTED_ORIGINS: ""
  FRONTEND_URL: ""
  POSTGRES_DB: "hims_kb_db"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
